### ISSUE TITLE
New style for GEO BON

### ISSUE THREAD

**Issue by timrobertson100** [gbif/eubon-ebv#3]
CM from UNEP WCMC requests that this be included in the http://geobon.org/essential-biodiversity-variables/what-are-ebvs/ page.

Please can we create a second HTML with the same functionality, but with GEOBON logo and "styled" appropriately for inclusion on that site?

@MortenHofft Could you please do that?

**Comment by MortenHofft** [comment]
geobon style added. see https://github.com/gbif/eubon-ebv/blob/master/backend/src/main/resources/assets/geobon.html and https://github.com/gbif/eubon-ebv/blob/master/backend/src/main/resources/assets/geobon.css
