### ISSUE TITLE
Migrate to PostgreSQL

### ISSUE THREAD

**Issue by MattBlissett** [gbif/eubon-ebv#4]
This is close to becoming the only system using our MySQL server.

I think it would be easy to migrate to PostgreSQL, it is just two tables.  Should I do this — I'd probably just move the data — or would you prefer to? Maybe to also refresh the data.

**Comment by timrobertson100** [comment]
If you wouldn't mind... can you?

It's fairly self explainatory here, on how to refresh the data:
  https://github.com/gbif/eubon-ebv/tree/master/backend/db

And should any SQL need changed to be PG compliant see:
  https://github.com/gbif/eubon-ebv/blob/master/backend/src/main/java/org/gbif/eubon/ebv/data/DataDAO.java

And obviously the JDBC driver change.

**Comment by MattBlissett** [comment]
Was done in https://github.com/gbif/eubon-ebv/commit/5c657e0b70c33677d108ea72c99370b2167ab05b
